name: skynet_internet_cafe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.5
  flutter_bloc: ^8.1.6
  fl_chart: ^1.1.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # for assets
  # assets:
  #   - assets/

  # for custom font
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont.ttf
